server:
  port: 8888

ying:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: screen_flicker
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 888888
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
  mail:
    host: smtp.qq.com
    port: 465
    default-encoding: UTF-8
    username: 123456@qq.com
    protocol: smtp
    password: laasrbxbnlpnbjda
    mail-verify:
      ip: http://localhost:8888/client/user/verifyMail/
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

upload:
  local:
    directory: service-zt/src/main/resources/static/video
    temp: service-zt/src/main/resources/static/temp

